algoritmo "semnome"
// Fac¸a um algoritmo que leia a altura e o raio de um cone,
//calcule e mostre seu volume.
var
n1,n2:real

inicio
escreva ("digite o primeiro numero: ")
leia (n1)
escreva ("digite o segundo numero: ")
leia (n2)
se n1=n2 entao
   escreva ("os numeros são iguais")
senao
   se n1>n2 entao
      escreval ("o primeiro numero digitado é maior:", n1)
   senao
      escreval ("o segundo numero digitado é maior:", n2)
   fimse
fimse
fimalgoritmo
