algoritmo "semnome"
// Fac¸a um algoritmo que receba a idade de 5 pessoas e mostre mensagem informando
// "maior de idade" e "menor de idade" para cada pessoa.
// Considere a idade a partir de 18 anos como maior de idade.
var
idade,contador:inteiro
inicio
para contador de 1 ate 5 faca
escreval ("qual a idade a ser verificada: ")
leia (idade)
se idade>=18 entao
escreval ("maior de idade ")
senao
escreval ("menor de idade ")
fimse
fimpara
fimalgoritmo
