algoritmo "aula_3_prog_1"
// Função :
// Autor :
// Data : 24/8/2016
// Seção de Declarações 
var

nome: caracter
num_carros, valor_vendas, total: real

inicio
// Seção de Comandos 
escreval ("Digite o nome do vendedor:")
leia (nome)
escreval("digite total de vendas: ")
leia (valor_vendas)
escreval("numero de carros: ")
leia (num_carros)
total<-500+(num_carros*50)+(valor_vendas*0.05)
escreval ("o vendedor: ", nome, "vendeu neste mês: ", total, " reais")



fimalgoritmo
