algoritmo "semnome"
// Obtenha um nu´mero digitado pelo usua´rio e repita a operac¸a~o de multiplicar ele por tre^s
//(imprimindo o novo valor) ate´ que ele seja maior do que 100. Ex.: se o usua´rio digita 5,
//deveremos observar na tela a seguinte seque^ncia: 5 15 45 135
var
n1:inteiro

inicio
escreva ("escreva um numero: ")
   leia (n1)
enquanto (n1<100)faca
    n1<-n1*3
   escreval ("valor atual: ",n1)
fimenquanto
fimalgoritmo
